name: CMake Build and Test on Windows with MinGW

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    env:
      MINGW_PATH: C:\msys64\mingw64\bin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up MinGWcd port/windows-h4
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-portaudio
            winpty
      - name: Add MinGW to PATH
        run: echo "$MINGW_PATH" >> $GITHUB_PATH
      - name: Configure CMake
        run: |
          cmake -B build
      - name: Build
        run: |
          cmake --build build